### ISSUE TITLE
Replace huge animated GIFs with MP4 videos (or animated WebP)

### ISSUE THREAD

**Issue by niutech** [rendicott/uggly-client#1]
For the sake of users with low bandwidth, please replace huge animated GIF on your website with much smaller MP4 files:

http://uggly.bytester.net/img/demo-astro.gif is 44 MB -> https://giant.gfycat.com/AmpleOrganicHorsefly.mp4 is 11 MB
http://uggly.bytester.net/img/demo-login.gif is 55 MB ->  https://giant.gfycat.com/NecessaryPowerlessFruitfly.mp4 is 7 MB
https://github.com/rendicott/uggly-client/raw/master/img/demo.gif is 33 MB -> https://giant.gfycat.com/ViciousSickFish.mp4 is 7 MB

Thanks!

**Comment by rendicott** [comment]
Thanks. that makes more sense. 

What do you think of the project?
